project:
  type: website
  output-dir: _site

website:
  title: "Jorge I. Vélez"
  #favicon: "fa-duotone fa-dna"
  navbar:
    right:
      - href: about.qmd
        text: "About"
      - href: students.qmd
        text: ""
      - href: awards.qmd
        text: ""
      - href: media.qmd
        text: ""        
      - href: publications.qmd
        text: ""        
      #- publications.qmd

format:
  html:
    theme: spacelab # default cerulean cosmo cyborg darkly flatly 
                   # journal litera lumen lux materia minty 
                   # morph pulse quartz sandstone simplex sketchy
                   # slate solar spacelab superhero united vapor yeti zephyr
    css: styles.css
    toc: false
    toc-location: right
    toc-title: " "  
    number-sections: false
    code-copy: true

#editor: visual

